export const GAME_CONSTANTS = {
  INITIAL_BANK: 1000,
  DEALER_STAND_THRESHOLD: 17,
  BLACKJACK_PAYOUT: 1.5, // 3:2 payout
  MIN_CARDS_BEFORE_SHUFFLE: 15,
  DELAYS: {
    DEALER_REVEAL: 800,
    DEALER_HIT: 1000,
    RESULTS_SHOW: 1000,
  }
};
